# Generated by Django 5.2.12 on 2026-09-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_verified_user_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_otp',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
