# Generated by Django 5.2.12 on 2026-09-02 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='password_hash',
            new_name='password',
        ),
    ]
