# Generated by Django 5.2.12 on 2026-09-09 11:22

import apps.quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_rename_password_hash_quiz_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_code',
            field=models.CharField(default=apps.quizzes.models.Quiz.generate_quiz_code, editable=False, max_length=6, unique=True),
        ),
    ]
