# Generated by Django 5.2.12 on 2026-09-14 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_quiz_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['teacher', 'status'], name='quiz_teacher_st'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='quiz_st_dates'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['quiz_code'], name='quiz_code_idx'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'order'], name='quiz_q_order'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['quiz', 'question'], name='quiz_q_composite'),
        ),
    ]
