# Generated by Django 5.2.12 on 2026-10-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_quiz_quiz_teacher_st_quiz_quiz_st_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_usages', to='quizzes.question'),
        ),
    ]
