# Generated by Django 5.2.12 on 2026-09-09 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0003_alter_quiz_quiz_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired'), ('EVALUATED', 'Evaluated')], default='IN_PROGRESS', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('submit_idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='quizzes.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('NOT_ANSWERED', 'Not Answered'), ('ANSWERED', 'Answered'), ('PENDING', 'Pending'), ('EVALUATED', 'Evaluated')], default='NOT_ANSWERED', max_length=20)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True)),
                ('execution_result', models.JSONField(blank=True, null=True)),
                ('evaluated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_answers', to='quizzes.question')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='students.examattempt')),
            ],
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'quiz', 'status'], name='att_stu_quiz_st'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['quiz', 'status'], name='att_quiz_st'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['student', 'status'], name='att_stu_st'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['expires_at'], name='att_expires'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('student', 'quiz', 'attempt_number'), name='uniq_attempt_num'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'status'], name='ans_attempt_st'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['attempt', 'sequence'], name='ans_attempt_seq'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='ans_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_ans_question'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('attempt', 'idempotency_key'), name='uniq_ans_idem'),
        ),
    ]
