# Generated by Django 5.2.12 on 2026-10-06 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quizquestion_question'),
        ('students', '0002_examattempt_blocked_at_examattempt_is_blocked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_answers', to='quizzes.question'),
        ),
    ]
