# Generated by Django 5.2.12 on 2026-03-13 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('quiz_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time_limit', models.IntegerField(blank=True, help_text='Time in minutes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
