# Generated by Django 5.2.12 on 2026-03-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_option_quizattempt_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='review_on',
            field=models.BooleanField(default=True),
        ),
    ]
