# Generated by Django 5.2.12 on 2026-03-15 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_quiz_review_on'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('attempt', 'question')},
        ),
    ]
