# Generated by Django 5.2.12 on 2026-03-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_answer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_of_qus',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
