# Generated by Django 5.2.12 on 2026-03-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_quiz_num_of_qus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('msq', 'MSQ'), ('subjective', 'Subjective'), ('coding', 'Coding')], default='mcq', max_length=20),
        ),
    ]
