# Generated by Django 5.2.12 on 2026-03-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_answer_code_question_starter_code_testcase'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='language',
            field=models.CharField(default='python', max_length=10),
        ),
    ]
