# Generated by Django 5.2.12 on 2026-09-01 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_answer_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
